# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a2298d81e0d6727e1d1cc82c0da2c503f8601500821d1e2a14643a1ff4fa79e2071f969caf040988923da4b2f998d6c0aba631a802339a50f9ece38da8bc43e

test:
  secret_key_base: 2e8c349da0090fa6dde68b29a6ddfbc1eaeb604a5eceef06e632d3e276306de2ae314ba9039d78d2c3cd2d1d2c710aa3b11ba16593e0748024e57f62b3b0d871

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
